# general
dataset_path: "/data4T/ntanh/data/neu_surface_defect/NEU-CLS-64"
data_preprocess_path: "data/neu-cls-64/images_preprocessed_224"
le_path: "data/neu-cls-64/label_encoder.pickle" # label encoder model which converts string labels to integers.
fc1_path: "data/neu-cls-64/features/{}_fc1_features_std_pytorch_{}.pickle"
model: "RESNET50" # "VGG16" "RESNET50"
use_cache: False
use_histeq: True
image_size: 224
kmeans_k_cache_path: ".neu_cache/kmeans_acc_vs_k_tmp.pickle"
kmeans_n_init: 10
pca_component: 50
pca_whitten: True



